## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file Homework4-content.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (Homework4-content.sagetex.sage) was *autogenerated* from Homework4-content.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('Homework4-content', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()

