## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file T9-Content.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_188 = Integer(188); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_116 = Integer(116); _sage_const_29 = Integer(29); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_66 = Integer(66); _sage_const_43 = Integer(43); _sage_const_60 = Integer(60); _sage_const_132 = Integer(132); _sage_const_48 = Integer(48); _sage_const_81 = Integer(81); _sage_const_150 = Integer(150); _sage_const_159 = Integer(159); _sage_const_183 = Integer(183); _sage_const_197 = Integer(197); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_19 = Integer(19); _sage_const_54 = Integer(54); _sage_const_108 = Integer(108); _sage_const_99 = Integer(99); _sage_const_76 = Integer(76); _sage_const_127 = Integer(127); _sage_const_91 = Integer(91); _sage_const_200 = Integer(200); _sage_const_18 = Integer(18); _sage_const_142 = Integer(142); _sage_const_164 = Integer(164)## This file (T9-Content.sagetex.sage) was *autogenerated* from T9-Content.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('T9-Content', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_1 
_st_.blockbegin()
try:

 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 #Default Wild cards
 w0 = SR.wild(_sage_const_0 )


 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))

 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a



 #
except:
 _st_.goboom(_sage_const_29 )
_st_.blockend()
_st_.current_tex_line = _sage_const_23 
_st_.blockbegin()
try:
 q1c1 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q1c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q1c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q1c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q1c5 = RandInt(_sage_const_0 ,_sage_const_1 )
 q1c6 = RandInt(_sage_const_0 ,_sage_const_1 )
 q1c7 = RandInt(_sage_const_1 -q1c6,_sage_const_1 )
 q1c8 = RandInt(_sage_const_1 -q1c5,_sage_const_1 )

 q1f1 = q1c5*(x - q1c1 - _sage_const_1 ) + _sage_const_1 
 q1f2 = q1c6*(x - q1c2 - _sage_const_1 ) + _sage_const_1 
 q1f3 = q1c7*(x - q1c3 - _sage_const_1 ) + _sage_const_1 
 q1f4 = q1c8*(x - q1c4 - _sage_const_1 ) + _sage_const_1 

 q1p = expand(q1f1*q1f2*q1f3*q1f4)

 q1ans1 = q1c5 + q1c6 + q1c7 + q1c8
 q1ans2 = q1c5*q1c1 + q1c6*q1c2 + q1c7*q1c3 + q1c8*q1c4

except:
 _st_.goboom(_sage_const_43 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_0 , latex(q1p(x)))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.current_tex_line = _sage_const_54 
 _st_.inline(_sage_const_1 , latex(q1ans1))
except:
 _st_.goboom(_sage_const_54 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_2 , latex(q1ans2))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_60 
 _st_.inline(_sage_const_3 , latex((q1f1*q1f2*q1f3*q1f4)(x)))
except:
 _st_.goboom(_sage_const_60 )
_st_.current_tex_line = _sage_const_66 
_st_.blockbegin()
try:
 q2c1 = RandInt(_sage_const_1 ,_sage_const_5 )

 q2f1 = x**_sage_const_4  - q2c1**_sage_const_4 

 q2ans1 = _sage_const_2 *(q2c1)**(_sage_const_1 /_sage_const_2 )
 q2ans2 = x**_sage_const_2  + q2c1**_sage_const_2 
 q2ans3 = x + q2c1
 q2ans4 = x - q2c1

except:
 _st_.goboom(_sage_const_76 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_81 
 _st_.inline(_sage_const_4 , latex(q2f1(x)))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_5 , latex(-q2c1))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_6 , latex(q2c1))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_7 , latex(-q2c1))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_8 , latex(q2c1))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_9 , latex(q2ans2))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_10 , latex(q2ans3))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_11 , latex(q2ans4))
except:
 _st_.goboom(_sage_const_108 )
_st_.current_tex_line = _sage_const_116 
_st_.blockbegin()
try:
 q3c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )

 q3f1 = x**_sage_const_3  - q3c1**_sage_const_3 

 q3ans1 = -q3c1 / _sage_const_2  - _sage_const_3 **(_sage_const_1 /_sage_const_2 )*(q3c1 / _sage_const_2 )*i
 q3ans2 = -q3c1 / _sage_const_2  + _sage_const_3 **(_sage_const_1 /_sage_const_2 )*(q3c1 / _sage_const_2 )*i

 q3ans3 = x**_sage_const_2  + q3c1*x + q3c1**_sage_const_2 
 q3ans4 = x - q3c1

except:
 _st_.goboom(_sage_const_127 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_12 , latex(q3f1(x)))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_142 
 _st_.inline(_sage_const_13 , latex(q3c1))
except:
 _st_.goboom(_sage_const_142 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_14 , latex(q3ans1))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_15 , latex(q3ans2))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_159 
 _st_.inline(_sage_const_16 , latex(q3ans3))
except:
 _st_.goboom(_sage_const_159 )
try:
 _st_.current_tex_line = _sage_const_159 
 _st_.inline(_sage_const_17 , latex(q3ans4))
except:
 _st_.goboom(_sage_const_159 )
_st_.current_tex_line = _sage_const_164 
_st_.blockbegin()
try:
 q4c1 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q4c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q4c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q4c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 q4c5 = NonZeroInt(-_sage_const_3 ,_sage_const_3 )
 q4c6 = NonZeroInt(-_sage_const_3 ,_sage_const_3 )
 q4c7 = NonZeroInt(-_sage_const_3 ,_sage_const_3 )
 q4c8 = NonZeroInt(-_sage_const_3 ,_sage_const_3 )

 q4f1 = q4c5*x - q4c1
 q4f2 = q4c6*x - q4c2
 q4f3 = q4c7*x - q4c3
 q4f4 = q4c8*x - q4c4

 q4p = expand(q4f1*q4f2*q4f3*q4f4)

 q4ans1 = q4c1/q4c5 + q4c2/q4c6 + q4c3/q4c7 + q4c4/q4c8
 __tmp__=var("x"); q4ans2 = symbolic_expression((q4f1*q4f2*q4f3*q4f4)(x)).function(x)
except:
 _st_.goboom(_sage_const_183 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_188 
 _st_.inline(_sage_const_18 , latex(q4p(x)))
except:
 _st_.goboom(_sage_const_188 )
try:
 _st_.current_tex_line = _sage_const_197 
 _st_.inline(_sage_const_19 , latex(q4ans1))
except:
 _st_.goboom(_sage_const_197 )
try:
 _st_.current_tex_line = _sage_const_200 
 _st_.inline(_sage_const_20 , latex(q4ans2(x)))
except:
 _st_.goboom(_sage_const_200 )
_st_.endofdoc()

